### ISSUE TITLE
Feature suggestion: encode AES key.

### ISSUE THREAD

**Issue by nullptr-31** [AKushWarrior/steel_crypt#10]
I couldn't find a method to **encode AES** key to **store** it as a **string**. Is it possible to add this? I would like to be able to store AES key in my database.

**Comment by AKushWarrior** [comment]
What do you mean? `CryptKey().genFortuna(32)` returns a String. The AES algorithm takes a String as a key.

**Comment by nullptr-31** [comment]
Hi, thanks for you quick reply. i figured that out today. I was just
feeling a bit stupid yesterday. Again, I'm really sorry.

Le ven. 20 déc. 2019 02:33, Aditya Kishore <notifications@github.com> a
écrit :

**Comment by AKushWarrior** [comment]
That's okay.
