### ISSUE TITLE
encodeKeyToString returns a string with 4 double quotes (2 starting, 2 ending)

### ISSUE THREAD

**Issue by hb0nes** [AKushWarrior/steel_crypt#15]
```dart
return '""-----BEGIN PUBLIC KEY-----\r\n$dataBase64\r\n-----END PUBLIC KEY-----""';
```
Is a weird thing to do.
The parseKeyFromString method does not correctly parse the output of encodeKeyToString and results in an error. 
See https://pub.dev/documentation/flutter_cipher/latest/flutter_cipher/RSAKeyParser/parse.html

It doesn't expect those double quotes.

**Comment by AKushWarrior** [comment]
Whoops, should be an easy bugfix. Will do it later today...

**Comment by AKushWarrior** [comment]
I finished this with the latest update. Sorry it took a while.
