### ISSUE TITLE
AES string only input limits key options

### ISSUE THREAD

**Issue by borisgrekov** [AKushWarrior/steel_crypt#16]
We are only able to input string key to AesCrypt, which will most probably come encoded as base64ulr from the key generator. That is 6 bits of information per character. 

https://github.com/AKushWarrior/steel_crypt/blob/dea1f41633b4f618a88794268c9d52047188b674/lib/src/aes.dart#L74
At this stage this get converted to a Unit8List where the first two bits will always be 0 thus reducing the possible key space by 1/4. We then assume we are using a 256bit key where it is only equivalent to 192 bit key.

Suggestion: Enable passing a raw key or sting encoded using base64url and convert it to bytes accordingly.

**Comment by AKushWarrior** [comment]
I fixed this, but not in the way you suggested. Now, key generation and parsing all uses UTF-16 codes, which are 8 bits per char. This avoids any lossy conversions.
