### ISSUE TITLE
Decrypting using either RSAKeys

### ISSUE THREAD

**Issue by KenV1040** [AKushWarrior/steel_crypt#18]
Hello,

Looking through the documentation and examples, I can't find a way of decrypting an RSA encrypted message with someone's public key, since the decrypt function specifically specifies RSAPrivateKey. This function would be useful for when implementing end-to-end encryption where the sender encrypts with their private key, and the other receiver decrypts with the sender's public key. Is it possible for you to implement this feature? And hopefully also on the encryption function as well so it supports encrypting/decrypting with both RSAPublicKey and RSAPrivateKey. 

Thanks!

Edit: I just made my own function to do this, so no need to rush this

**Comment by AKushWarrior** [comment]
Hmmm...
You should never be able to decrypt with a Public Key. That's one of the core tenets of asymmetric encryption.

**Comment by akshat-khare** [comment]
But isn't the whole purpose of signing involves decrypting with public key?

**Comment by AKushWarrior** [comment]
You encrypt with a publicKey. Decrypt with a privateKey.

If you could decrypt with the same key that you encrypt with, it's no longer asymmetric. It's a symmetric algorithm.
