### ISSUE TITLE
RSACrypt Invalid argument(s): Input data too large

### ISSUE THREAD

**Issue by kedaly** [AKushWarrior/steel_crypt#21]
I'm trying to encrypt a string, it's not very long and I'm getting an Input Data Too large error.

`
final String ENC_TEST_DATA = '''
sdsgasfgfsghasjghsjdghkjshgkjasdhgksadhgjksdhgkjsdhgkjsdhgkjshgkshgksfhgjkfshgjkshfgkjhfsgafsgsafghfsjgs
fgjjghkjasfghkjashgkjashgkjshgkjshgjkshgkjshgkjshgkjashgkjhasgkjhasfkgjhasfjkghasfkjghfsakjghasfkjghfsgfsg
ahsgkjhsfjkghsfkjghkjsfghkjsfgasgafsgaskjghkjsahgkjshgkjshgkjshgkjshgksgsg
sghskdjhgkjsdhgksdhgkashgkshgkhasgkjdshgkjhsdgkjhwiutwuituwighkjfhgkjashowetoojashgjksdahgkjshgkjshg
gsdgjshgjksdhgjsdhgkjsdhgjksdhkjghsdkjghsdkjgsdkjhgkjsdhgkjsdhgjksdhgkjdshgkjsdgjksdhgkjhsdkgjhdskjgsdgksjdhgsd
sgjsdakgjhsakjghaskjghaskjghsakjghkjadshgkjsadhgkjwehoutewuuweghwjkghewuosdghsdjhgoeureoghsjkghkjsd
''';

final String ENC_TEST_DATA_BOB = ENC_TEST_DATA+"FOR BOB";
final String ENC_TEST_DATA_SUZIE = ENC_TEST_DATA+"FOR SUZIE";
...
    var encodedForBob = rsaCrypt.encrypt(ENC_TEST_DATA_BOB, bobsPublicKey);`

What's the longest length for rsaCrypt.encrypt?

**Comment by AKushWarrior** [comment]
It depends on how long the key is, and also how data is encoded. I don't really have more to say than that... This is really a question about RSA, not about steel_crypt.
