### ISSUE TITLE
could you add ECC 

### ISSUE THREAD

**Issue by note8g2018** [AKushWarrior/steel_crypt#24]
Hi Sir,

Could you please add ECC asymmetric two-way encryption, decryption to this Library, because I read that it is better thas RSA. and Thank you any way.

My source that I read:
https://gist.github.com/atoponce/07d8d4c833873be2f68c34f9afc5a78a
https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html

Best Regrades,

**Comment by AKushWarrior** [comment]
Better than RSA? 

Cryptographically, I don't see it; RSA is secure and an industry standard as of today.

The links are right insofar as implementation is trickier in RSA, but RSA is used by significantly more people than ECC. I will look into adding ECC, but I won't promise anything yet.

**Comment by AKushWarrior** [comment]
Okay, change of plans. As you may or may not know, I'm creating a 2.0 of this package (#22). I'm adding a new ECC class to the list of TODO's for 2.0. This would become `EccCrypt`.

**Comment by AKushWarrior** [comment]
I'm deprecating asymmetric functionality; it's too much work for me to maintain. https://pub.dev/crypton would be a good place to repost this issue.
