### ISSUE TITLE
Why enforcing base64 encoding?

### ISSUE THREAD

**Issue by denis-evteev** [AKushWarrior/steel_crypt#26]
First of all, thanks for taking time to write your awesome library!

I’m a bit puzzled with the fact that all hashing methods in the library return base64-encoded strings. So in fact instead of returning plain hashes, these methods return encoded hashes, and this doesn’t seem to be documented.

This is especially misleading when using password hashing methods, for which a hash length could be specified, but which return a value of different length (because of encoding), so to get the actual hash value, a base64-decoding of the returned value must be performed.

Could you please make base-64 encoding optional, maybe by adding a boolean argument to the existing hashing methods?

**Comment by AKushWarrior** [comment]
The issue is I don't want to return dynamic from the function, which I'd have to do.

I'm thinking of creating raw classes, which take and return `Uint8List`s. That's how data is handled internally, so it wouldn't be a ton of work.

In the meantime, should I document how I encode/decode strings?

**Comment by AKushWarrior** [comment]
Okay, change of plans. As you may or may not know, I'm creating a 2.0 of this package (#22). I'm adding new Raw classes to the list of TODO's for 2.0. This would become `RawAesCrypt`, `RawHashCrypt`, `RawLightCrypt`, etc. These classes would take and return only Uint8Lists, and users would be free to parse the results as they see fit.

**Comment by denis-evteev** [comment]
That sounds like a good idea.

Re documenting — I think that simply mentioning the fact that all methods get in and return base64-encoded strings should do for now.

**Comment by AKushWarrior** [comment]
Done in 2.0.
