### ISSUE TITLE
RSA/None/OAEPWithSHA-256AndMGF1Padding

### ISSUE THREAD

**Issue by sarbagyastha** [AKushWarrior/steel_crypt#31]
Is there any way to support encryption using RSA/None/OAEPWithSHA-256AndMGF1Padding algorithm, which is from Java's JCE?

**Comment by AKushWarrior** [comment]
I don't know. I'll look into it.

Edit: Okay, this will take some significant work. I'll mark this as wontfix for now, although I might revisit in the future. Maybe after steel_crypt 2.0 is out?

**Comment by sarbagyastha** [comment]
Okay. Any timeline for 2.0 ?

**Comment by AKushWarrior** [comment]
Approx. three weeks for 2.0.

I would need another week or so to add this, if I decide to do it.

**Comment by AKushWarrior** [comment]
Super-sorry about the jerk-around, but I've decided to deprecate RSA. You can read my reasoning on the README, and maybe refile this issue at https://pub.dev/packages/crypton

**Comment by sarbagyastha** [comment]
@AKushWarrior No problem. Found a workaround already.

**Comment by AKushWarrior** [comment]
Good for you. Mind posting it (on GitHub or elsewhere)? Interested in reading the code.
