### ISSUE TITLE
Get iv automatically

### ISSUE THREAD

**Issue by newdev8** [AKushWarrior/steel_crypt#33]
In PHP I use open_ssl to encrypt a file with AES256 CBC and the PKCS7 Padding.
The function automatically puts the iv on the start of the file for each block. Is there a way to get it automatically on the dart side?

In total there can be like 20 iv's or so.
How do I make your function AesCrypt.decrypt get automatically the iv for each block?

**Comment by AKushWarrior** [comment]
No way to get it automatically, I'm afraid.

When steel_crypt 2.0 is done, I can write up a parsing utility for you. Just give me an example encrypted file.

**Comment by newdev8** [comment]
You want an encrypted file alone or you want me to show you my php function?

**Comment by AKushWarrior** [comment]
Just the encrypted file (as a String). Bonus if you can show me where the iv is (section of the file String).

**Comment by newdev8** [comment]
I ended up using just one IV for simplicity, thanks anyways for the proposal of the utility.

**Comment by AKushWarrior** [comment]
DON'T DO THAT! Using just one IV will compromise the security of the entire system!

Edit: Overreaction, sorry. Are you using the one key as well? Because then it really is very insecure.

**Comment by newdev8** [comment]
No sorry, I din't mean literally just ONE iv, I meant the one your system provides, but also with your encryption functions.
