### ISSUE TITLE
FormatException: Invalid character

### ISSUE THREAD

**Issue by newdev8** [AKushWarrior/steel_crypt#34]
Does this library support special characters? (WÜ×¼B¦ç"·Àá|óË}x`À?¹ÝRÖYEKÛ)

**Comment by AKushWarrior** [comment]
can you post your code and the debug log?

**Comment by AKushWarrior** [comment]
As of right now, it supports all valid UTF-16 chars. The specific way to do this may change in the future with steel_crypt 2.0, though there will still be a way to use UTF-16 in 2.0.
