### ISSUE TITLE
How to use AES mode ECB with ZeroPadding

### ISSUE THREAD

**Issue by LucasManerich** [AKushWarrior/steel_crypt#37]
Hello,
I have this code in JavaScript:
```
encode(text, key) {
  let cipher = CryptoJS.enc.Utf8.parse(text);
  let flags = CryptoJS.enc.Utf8.parse('');

  let result = CryptoJS.AES.encrypt(key, cipher, { iv: flags, mode: CryptoJS.mode.ECB, padding: CryptoJS.pad.ZeroPadding });
  return result.toString();
}
```

I need to run in DART but this package does not have ZeroPadding, anyone can help me?

**Comment by AKushWarrior** [comment]
ECB is insecure. ZeroPadding has a 50% chance of losing some data. Neither is recommended.

Given that some others have asked for this, I will consider adding it. It's very easy to implement, but I'd rather not expose options which could lead to data loss.
