### ISSUE TITLE
Cannot call has pass in PBKDF2 mode

### ISSUE THREAD

**Issue by gabrielchiquini** [AKushWarrior/steel_crypt#38]
I am getting the error `Unhandled Exception: type 'ScryptParameters' is not a subtype of type 'Pbkdf2Parameters' of 'params'` in version 2.0.0 beta.
I've found a possible cause in code. On file lib/src/encoded/pass.dart, the algorithm for PBKDF2 is set as P, on line [49](https://github.com/AKushWarrior/steel_crypt/blob/master/lib/src/encoded/pass.dart#L49), but on line [61](https://github.com/AKushWarrior/steel_crypt/blob/master/lib/src/encoded/pass.dart#L61) the code is checking if algorithm contains PBKDF2, which will never be true, because it's set with P, then the error occurs.
I think this can be a bug.

**Comment by AKushWarrior** [comment]
This is why we have beta. Somehow, this passed me by. I'll add it to my to-do list.

**Comment by gabrielchiquini** [comment]
Thank you, I will use scrypt for while.

**Comment by AKushWarrior** [comment]
This is done in the latest commit. Will upload to pub.dev in a minute.

**Comment by gabrielchiquini** [comment]
Thank you for solving this quick
