### ISSUE TITLE
RegistryFactoryException when calling HashCrypt(algo: HashAlgo.Sha3_256).hash(inp: username)

### ISSUE THREAD

**Issue by edwin-alvarez** [AKushWarrior/steel_crypt#42]
I tried to implement a static key using username, see the example below. but, I get RegistryFactoryException 

```
  static String getKey(String username) {
    var dbKey = HashCrypt(algo: HashAlgo.Sha3_256).hash(inp: username);

    return dbKey;
  }
```

I'm referring to this code example:
https://github.com/AKushWarrior/steel_crypt/issues/35, another thing i noticed was they use getFromMap, which I have not idea what it should do

<details>
<summary>
Environment:
</summary>
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

• No issues found!
</details>

What am I trying to do?
I'm trying to implement a small method that uses userID/PWD to store and retrieve data from an SQFLITE storage. The idea I have is to use have is to aes.ctr to encrypt. Then, send the data to the storage, finally when querying, I will use aes.ctr.decrypt.

I noticed that my mEncrypt is working, but mDecrypt does not, I'm pretty sure it is due to the genFortuna uses a new key, which is different from the original used for Encrypt

```
voud mEncrypt {
    var keyGen = CryptKey();
    var key32 = keyGen.genFortuna(len: 32);
    var aes = AesCrypt(key: key32, padding: PaddingAES.pkcs7);
    var iv16 = keyGen.genDart(len: 16);
    var crypted2 = aes.ctr.encrypt(inp: text, iv: iv16); //Encrypt.
}

voud mDecrypt {
     var keyGen = CryptKey();
    //generate 32 byte key using Fortuna
    var key32 = keyGen.genFortuna(len: 32);

    // generated AES encrypter with key + padding
    var aes = AesCrypt(key: key32, padding: PaddingAES.pkcs7);
    //generate iv for AES
    var iv16 = keyGen.genDart(len: 16);
    var decrypt = aes.ctr.decrypt(enc: text, iv: iv16); //Decrypt.
}
```

**Comment by edwin-alvarez** [comment]
?

**Comment by AKushWarrior** [comment]
@edwin-alvarez you need to store the key somewhere - I recommend https://pub.dev/packages/flutter_secure_storage

**Comment by edwin-alvarez** [comment]
@AKushWarrior , I dont think, you understood my problem. I have a user name and pwd and i want to use that to encrypt the data that is stored in an SQLFLITE data. 

how do I use user name/pwd to generate a key for aes.ctr.decrypt? i try the method i pasted but looks like the HashCrypt throws RegistryFactoryException

**Comment by AKushWarrior** [comment]
I suggest you read up on password derivation. The algorithms for that purpose provided in this library are PBKDF2 and SCrypt. You should NEVER use normal hashing algorithms (SHA, Blake2b, etc.) for passwords. This isn't really an issue with the library, so I'm closing it. 

If you need some links for further reading on password derivation and how to make passwords into usable AES keys, I can find them.

**Comment by edwin-alvarez** [comment]
@AKushWarrior what I mean is that code in this other post https://github.com/AKushWarrior/steel_crypt/issues/35 is not sully supported in 2.0, do you have any example using latest version

**Comment by AKushWarrior** [comment]
> @AKushWarrior what I mean is that code in this other post https://github.com/AKushWarrior/steel_crypt/issues/35 is not sully supported in 2.0, do you have any example using latest version?

The code in #35 is still valid conceptually, but you didn't translate it correctly. You should not be using a username hashed using SHA-3 as a key for AES. 

What you can do is hash the password using Scrypt. The hashed password will also have the convenient property of being properly sized to be an AES key, so you can encrypt data based on the password.

The issue with this method is you need to store the hashed password and the salt, so you can check if future password attempts are correct. I recommend either storing in a username-password database, if you want to enable signing in from multiple devices, or in https://pub.dev/flutter_secure_storage if you just want to keep the data to one device.
