### ISSUE TITLE
Flutter web build  fails when including any version of steel crypt.

### ISSUE THREAD

**Issue by Mikailo** [AKushWarrior/steel_crypt#43]
Hello, I have encountered an issue when trying the flutter build web command and including any version of steel crypt(Specifically tried with 2.2.1 and 1.6.1) in the pubspec, even if it isn't used anywhere. 

![image](https://user-images.githubusercontent.com/37148156/91282207-b7e90f80-e791-11ea-8a07-4c0e8e9c47f9.png)

Simply running a web server works without issues.

These are other dependencies , that I have included in my project if that helps.

![image](https://user-images.githubusercontent.com/37148156/91282926-a0f6ed00-e792-11ea-8843-a5a93677db29.png)

**Comment by AKushWarrior** [comment]
This issue is an upstream issue with pointycastle. I can fix it real quick... Give me a day or so.

**Comment by Mikailo** [comment]
Hello, sorry to pester you,but is there any progress with this issue?

**Comment by MoyaMaker** [comment]
This error still appearing, any update?

**Comment by AKushWarrior** [comment]
@Mikailo @MoyaMaker Should be fixed in v2.3.0. I was trying to hold off on publishing a new version until I finished writing the documentation, but I simply haven't had the time to sit down and do that.

**Comment by AKushWarrior** [comment]
Wait, not done. For some reason, pointycastle is import dart:io upstream. I'll have to figure out a fix for that (or maybe move to js interop for web).

**Comment by hectorvillag** [comment]
I think this was solved in the this pull request [here](https://github.com/bcgit/pc-dart/pull/41)

**Comment by AKushWarrior** [comment]
That PR appears to have been merged and published. Updating the version constraints for pointycastle in this library will probably solve this issue.

**Comment by AKushWarrior** [comment]
This should work now.
