### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by OroshiX** [AKushWarrior/steel_crypt#49]
Is there a plan in the near future for null safety in this package?  
Null safety is now fully launched with flutter 2.

**Comment by AKushWarrior** [comment]
Yeah, I'm going to be working on it this weekend. If all goes well, you can expect to see it by the end of next week.

**Comment by Skyost** [comment]
Any news @AKushWarrior ?

**Comment by AKushWarrior** [comment]
I've started it. I estimate I'm about halfway done right now.

**Comment by OroshiX** [comment]
Any updates?

**Comment by AKushWarrior** [comment]
Thanks for reminding me. I had a preliminary version done on my machine, but I forgot to publish it. It's out as of now on both GitHub and pub.dev.
