### ISSUE TITLE
Wrong password for decryption raises FormatException (Clarification)

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [AKushWarrior/steel_crypt#51]
Decryption with corrrect password works flawlessly but wrong password for decryption in AES raises FormatException , is this an expected behaviour?

**Comment by AKushWarrior** [comment]
Yeah. If you put in the wrong key, the decryption behavior is actually unspecified. It could either return gibberish (unlikely) or throw an error (more likely).

If this is something that happens regularly, I recommend you just wrap decryption in a try-catch that will display a "wrong password" message.

**Comment by TheSeriousProgrammer** [comment]
Yes that's what I did , thanks for the awesome library!!
