### ISSUE TITLE
Feature suggestion: encoding to PEM

### ISSUE THREAD

**Issue by KenV1040** [AKushWarrior/steel_crypt#8]
After having read the documentation, I don't think you have a method to encode public and private key to PEM and storing it as a string. Is it possible to add this? I'd like to use this feature so I can store it in FlutterSecureStorage since it only accepts strings.

**Comment by AKushWarrior** [comment]
I'll try to figure out a way to do this. Right now, I think JSON string encoding/decoding might be the easiest way to do this, but I'll take a look at PEM, since PEM is more standardized.

**Comment by KenV1040** [comment]
Alright, thanks for the suggestion. I'll check it out!

**Comment by AKushWarrior** [comment]
Right, so I can definitely make PEM encoding work. I'm unit testing now, but PEM encoding will be in the main lib within the next few hours.

**Comment by AKushWarrior** [comment]
The update (which is not on github yet, I have some versioning stuff to work out) is now on pub. 
 To convert a key to a PEM string, use 
```dart
RsaCrypt().encodeKeyToString(RsaAsymmetricKey KeyHere)
```

To get a key back from a PEM string, use 
```dart
RsaCrypt().parseKeyFromString(String PemStringHere)
```
